import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "./components/shared/ThemeRegistry";
import ReduxProvider from "./providers/store.provider";

export const metadata: Metadata = {
  title: "Conexa App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeRegistry options={{ key: "mui" }}>
            
            {children}
          </ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
